import Link from 'next/link';
import { BookOpen, Users, Award } from 'lucide-react';

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero Section */}
      <header className="bg-white shadow-sm">
        <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center">
            <BookOpen className="h-8 w-8 text-primary" />
            <span className="ml-2 text-xl font-bold text-gray-900">EduTech AI</span>
          </div>
          <div className="flex space-x-4">
            <Link href="/courses" className="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium">
              Browse Courses
            </Link>
            <Link href="/auth/login" className="text-primary hover:text-primary/80 px-3 py-2 rounded-md text-sm font-medium">
              Login
            </Link>
            <Link href="/auth/register" className="bg-primary text-white hover:bg-primary/90 px-4 py-2 rounded-md text-sm font-medium">
              Sign Up
            </Link>
          </div>
        </nav>
      </header>

      <main>
        <div className="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-tight lg:text-6xl">
              Master New Skills with <span className="text-primary">AI-Powered Learning</span>
            </h1>
            <p className="mt-4 max-w-2xl mx-auto text-xl text-gray-500">
              Create and take courses generated by advanced AI. Personalized learning paths, instant content generation, and expert educators.
            </p>
            <div className="mt-8 flex justify-center gap-4">
              <Link href="/courses" className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-primary hover:bg-primary/90">
                Start Learning
              </Link>
              <Link href="/auth/register" className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-primary bg-accent/30 hover:bg-accent/50">
                Become an Educator
              </Link>
            </div>
          </div>
        </div>

        {/* Features */}
        <div className="bg-white py-16">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
              <div className="text-center">
                <div className="flex items-center justify-center h-12 w-12 rounded-md bg-primary text-white mx-auto">
                  <BookOpen className="h-6 w-6" />
                </div>
                <h3 className="mt-6 text-lg font-medium text-gray-900">AI Course Generation</h3>
                <p className="mt-2 text-base text-gray-500">
                  Educators can generate detailed syllabi and lesson content instantly using Gemini AI.
                </p>
              </div>
              <div className="text-center">
                <div className="flex items-center justify-center h-12 w-12 rounded-md bg-primary text-white mx-auto">
                  <Users className="h-6 w-6" />
                </div>
                <h3 className="mt-6 text-lg font-medium text-gray-900">Interactive Learning</h3>
                <p className="mt-2 text-base text-gray-500">
                  Engage with content, track progress, and chat with educators directly.
                </p>
              </div>
              <div className="text-center">
                <div className="flex items-center justify-center h-12 w-12 rounded-md bg-primary text-white mx-auto">
                  <Award className="h-6 w-6" />
                </div>
                <h3 className="mt-6 text-lg font-medium text-gray-900">Certified Skills</h3>
                <p className="mt-2 text-base text-gray-500">
                  Earn recognition for completing courses and mastering new topics.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
